# configs/config.yaml
data_dir: ./records               
robot_name: franka               
state_pub_addr: tcp://127.0.0.1:5555 
capture_interval: 0.001             

camera_streams:
  zed_left:
    address: tcp://127.0.0.1:6000    
    recv_timeout_ms: 1000            
